#-----------------------------------------------------------------------------------------------------
#                        DB PROPERTIES
#-----------------------------------------------------------------------------------------------------

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
